---
- name: Install Nginx and start server
  hosts: dbservers
  become: true
  
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Start Nginx
      service:
        name: nginx
        state: started
